-- Lista de las tres compañías aéreas menos puntuales (calculado en base al porcentaje de vuelos
-- retrasados

WITH retrasos_aerolineas AS (
    SELECT 
        AVION.AEROLINEA,
        COUNT(DISTINCT VUELO.ID_VUELO) AS NUM_VUELOS,
        COUNT(RETRASO.ID_INCIDENCIA) AS NUM_RETRASOS,
        COUNT(RETRASO.ID_INCIDENCIA) / COUNT(DISTINCT VUELO.ID_VUELO) AS PORCENTAJE_RETRASOS
    FROM VUELO
        INNER JOIN AVION ON AVION.MATRICULA = VUELO.AVION
        LEFT JOIN RETRASO ON RETRASO.ID_VUELO = VUELO.ID_VUELO
    GROUP BY AVION.AEROLINEA
)
SELECT AEROLINEA, NOMBRE
FROM retrasos_aerolineas r1
    INNER JOIN AEROLINEA ON AEROLINEA.CARRIER_CODE = r1.AEROLINEA
WHERE (
    SELECT COUNT(*)
    FROM retrasos_aerolineas r2
    WHERE r2.PORCENTAJE_RETRASOS > r1.PORCENTAJE_RETRASOS
) < 3;
