-- Aeropuertos que ha tenido el momento con mayor actividad, y momento en el que ha ocurrido. La
-- actividad de un aeropuerto se calcula en el horario estimado de salida de cada vuelo y consiste en el
-- número de aviones a menos de 15 minutos de despegar o aterrizar (según el horario estimado).



CREATE INDEX idx_vuelo_origen_destino ON VUELO (ORIGEN, DESTINO); -- Join entre ORIGEN Y DESTINO
CREATE INDEX idx_vuelo_salida_llegada ON VUELO (SALIDA, LLEGADA); -- Precalculo de SALIDA y LLEGADA

--EXPLAIN PLAN FOR

WITH ACTIVIDAD AS (
SELECT  AEROPUERTO.IATA AS AEROPUERTO, V1.SALIDA AS MOMENTO, COUNT(DISTINCT V2.ID_VUELO) AS NUMERO 
FROM VUELO V1, VUELO V2, AEROPUERTO
WHERE V1.ID_VUELO <> V2.ID_VUELO
    AND (V2.LLEGADA BETWEEN V1.SALIDA - 15/1440 AND V1.SALIDA + 15/1440 AND V1.ORIGEN = V2.DESTINO AND AEROPUERTO.IATA = V2.DESTINO)
    OR (V2.SALIDA BETWEEN V1.SALIDA - 15/1440 AND V1.SALIDA + 15/1440 AND AEROPUERTO.IATA = V2.ORIGEN AND V1.ORIGEN = V2.ORIGEN)
GROUP BY AEROPUERTO.IATA, V1.SALIDA
ORDER BY NUMERO DESC
),
maximoPeriodos AS(
SELECT DISTINCT ACTIVIDAD.MOMENTO AS MOMENTO, MAX(ACTIVIDAD.NUMERO) AS NUMERO
FROM ACTIVIDAD
GROUP BY ACTIVIDAD.MOMENTO
)
SELECT DISTINCT TO_CHAR(ACTIVIDAD.MOMENTO, 'DD/MM/YYYY HH24:MI:SS') AS MOMENTO, ACTIVIDAD.AEROPUERTO AS AEROPUERTO, ACTIVIDAD.NUMERO AS NUMERO
FROM ACTIVIDAD, maximoPeriodos
WHERE ACTIVIDAD.MOMENTO = maximoPeriodos.MOMENTO AND ACTIVIDAD.NUMERO = maximoPeriodos.NUMERO
ORDER BY NUMERO DESC;

--SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

DROP INDEX idx_vuelo_origen_destino;
DROP INDEX idx_vuelo_salida_llegada;