DROP TABLE RELACION;
DROP TABLE PELICULA;
DROP TABLE CAPITULO;
DROP TABLE SERIE;
DROP TABLE ACTOR;
DROP TABLE DIRECTOR;
DROP TABLE OTRO_ROL;
DROP TABLE GENERO;
DROP TABLE PERSONA;
DROP TABLE OBRA;

