
CREATE TABLE PERSONA (
    ID_PERSONA  VARCHAR(10)     CONSTRAINT PK_PERSONA   PRIMARY KEY,
    NOMBRE      VARCHAR(100)    NOT NULL,
    SEXO        VARCHAR(1),

    CONSTRAINT CHK_PERSONA_SEXO CHECK (SEXO IN ('m', 'f')));

CREATE TABLE OBRA (
    ID_OBRA     VARCHAR(10)     CONSTRAINT PK_OBRA PRIMARY KEY,
    TITULO      VARCHAR(200)    NOT NULL,
    AGNO        NUMBER(4),

    CONSTRAINT CHK_OBRA_AGNO CHECK (AGNO >= 1928));

CREATE TABLE GENERO (
    NOMBRE      VARCHAR(100),
    ID_OBRA     VARCHAR(10),

    CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE, ID_OBRA),
    CONSTRAINT FK_GENERO_OBRA FOREIGN KEY (ID_OBRA) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE);


CREATE TABLE PELICULA (
    ID_PELICULA     VARCHAR(5)     CONSTRAINT PK_PELICULA PRIMARY KEY,

    CONSTRAINT FK_PELICULA_OBRA FOREIGN KEY (ID_PELICULA) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE);


CREATE TABLE SERIE (
    ID_SERIE        VARCHAR(5)     CONSTRAINT PK_SERIE PRIMARY KEY,
    AGNO_INICIAL    NUMBER(4),
    AGNO_FINAL      NUMBER(4),

    CONSTRAINT FK_SERIE_OBRA FOREIGN KEY (ID_SERIE) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE,
    CONSTRAINT CHK_SERIE_AGNO_I CHECK (AGNO_INICIAL >= 1928),
    CONSTRAINT CHK_SERIE_AGNO_F CHECK (AGNO_FINAL >= 1928));

CREATE TABLE CAPITULO (
    ID_CAPITULO VARCHAR(5)     CONSTRAINT PK_CAPITULO PRIMARY KEY,
    ID_SERIE     VARCHAR(5)     NOT NULL,
    NOMBRE      VARCHAR(200),
    TEMPORADA   NUMBER(4),
    NUMERO      NUMBER(4),

    CONSTRAINT FK_CAPITULO_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE (ID_SERIE) ON DELETE CASCADE,
    CONSTRAINT CHK_CAPITULO_TEMPORADA CHECK (TEMPORADA >= 0),
    CONSTRAINT CHK_CAPITULO_NUMERO CHECK (NUMERO >= 0));


CREATE TABLE RELACION (
    ID_PELICULA    VARCHAR(5),
    ID_RELACIONADA VARCHAR(5),
    TIPO        VARCHAR(100),

    CONSTRAINT PK_RELACION PRIMARY KEY (ID_PELICULA, ID_RELACIONADA, TIPO),
    CONSTRAINT FK_RELACION_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA) ON DELETE CASCADE,
    CONSTRAINT FK_RELACION_RELACION FOREIGN KEY (ID_RELACIONADA) REFERENCES PELICULA (ID_PELICULA) ON DELETE CASCADE,
    CONSTRAINT CK_RELACION_IDS_DIFERENTES CHECK (ID_PELICULA <> ID_RELACIONADA));


CREATE TABLE ACTOR (
    ID_ACTOR    VARCHAR(10)     CONSTRAINT PK_ACTOR_ID_ACTOR PRIMARY KEY,
    ID_PERSONA  VARCHAR(10)     NOT NULL,
    ID_OBRA     VARCHAR(10)     NOT NULL,
    PERSONAJE   VARCHAR(100),

    CONSTRAINT FK_ACTOR_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA) ON DELETE CASCADE,
    CONSTRAINT FK_ACTOR_OBRA FOREIGN KEY (ID_OBRA) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE);


CREATE TABLE DIRECTOR (
    ID_DIRECTOR  VARCHAR(10)    CONSTRAINT PK_DIRECTOR  PRIMARY KEY,
    ID_PERSONA  VARCHAR(10)     NOT NULL,
    ID_OBRA     VARCHAR(10)     NOT NULL,

    CONSTRAINT FK_DIRECTOR_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA) ON DELETE CASCADE,
    CONSTRAINT FK_DIRECTOR_OBRA FOREIGN KEY (ID_OBRA) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE);


CREATE TABLE OTRO_ROL (
    ID_ROL      VARCHAR(10)     CONSTRAINT PK_OTRO_ROL_ID_ROL PRIMARY KEY,
    ID_PERSONA  VARCHAR(10)     NOT NULL,
    ID_OBRA     VARCHAR(10)     NOT NULL,
    ROL         VARCHAR(100),

    CONSTRAINT FK_OTRO_ROL_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA) ON DELETE CASCADE,
    CONSTRAINT FK_OTRO_ROL_OBRA FOREIGN KEY (ID_OBRA) REFERENCES OBRA (ID_OBRA) ON DELETE CASCADE);
