-- Listar el nombre de los directores que han dirigido al menos seis series distintas en la década de los 90.

-- -- from
-- CREATE OR REPLACE VIEW v_directores_90 AS
-- SELECT  PERSONA.NOMBRE, COUNT(DISTINCT SERIE.ID_SERIE) AS NUM_SERIES
-- FROM SERIE, CAPITULO, DIRECTOR, PERSONA
-- WHERE 
--    SERIE.ID_SERIE = DIRECTOR.ID_OBRA AND DIRECTOR.ID_PERSONA = PERSONA.ID_PERSONA AND
--    SERIE.AGNO_INICIAL >= 1990 AND SERIE.AGNO_INICIAL <= 1999
-- GROUP BY PERSONA.NOMBRE;


-- inner join
CREATE OR REPLACE VIEW v_directores_90 AS
SELECT  PERSONA.NOMBRE, COUNT(DISTINCT SERIE.ID_SERIE) AS NUM_SERIES
FROM DIRECTOR
   INNER JOIN PERSONA ON DIRECTOR.ID_PERSONA = PERSONA.ID_PERSONA
   INNER JOIN SERIE ON DIRECTOR.ID_OBRA = SERIE.ID_SERIE
WHERE SERIE.AGNO_INICIAL >= 1990 AND SERIE.AGNO_INICIAL <= 1999
GROUP BY PERSONA.NOMBRE;

-- query final
SELECT NOMBRE FROM v_directores_90 WHERE NUM_SERIES >= 6;
